---
title: "MTC_drug_screen"
author: "Yan Zhou"
date: "2025-03-04"
output: html_document
---

```{r setup}
library(survival)
library(survminer)
library(ggplot2)



```

```{r import}

sinfo = read.xlsx("input/MTC_total_sample_info_20240812.xlsx", sheet = 1)
df_combine = read.table("input/MTC_combined389samples_discovry_9380prots_20240424.csv", quote = "",sep = ",", row.names = 1, header = T)
names(df_combine) = sinfo$MS_ID[match(names(df_combine),sinfo$MS_File_name)]

uniprot = sapply(row.names(df_combine),function(v){strsplit(v,"_")[[1]][1]}) %>% as.vector()

```

```{r cluster - dunn test}

cluster = read.csv("rank3sample_cluster_extractFeatures.csv",row.names = 1)
c1 = cluster$sample[cluster$cluster =="1"]
c2 = cluster$sample[cluster$cluster =="2"]
c3 = cluster$sample[cluster$cluster =="3"]

df_cluster = data.frame(prot = row.names(df_combine))

## calculate mean values for each cluster
df_cluster$c1 = apply(df_combine,1,function(x){mean(x[names(df_combine) %in% c1])})
df_cluster$c2 = apply(df_combine,1,function(x){mean(x[names(df_combine) %in% c2])})
df_cluster$c3 = apply(df_combine,1,function(x){mean(x[names(df_combine) %in% c3])})

clu = cluster$cluster[match(names(df_combine),cluster$sample)]


# Dunn test 
library(FSA)
clu = as.factor(clu)
p_value_dunn = data.frame(prot = row.names(df_combine))

for (i in 1:9380) {
  # prot = row.names(df_combine)[i]
  dunn = ifelse(identical(df_cluster[i,2],df_cluster[i,3],df_cluster[i,4]),
                NA,
                apply(df_combine[i,],1,function(x){dunnTest(x ~ clu,method = "bh")})
  )
  p_value_dunn[i,2:4] = ifelse(is.na(dunn),NA,dunn[[1]][["res"]][["P.adj"]] )
}

p_value_dunn$adj_p_12 = p.adjust(p_value_dunn$V2, method = "BH")
p_value_dunn$adj_p_13 = p.adjust(p_value_dunn$V3, method = "BH")
p_value_dunn$adj_p_23 = p.adjust(p_value_dunn$V4, method = "BH") 
  
P_sig_dunn = p_value_dunn[p_value_dunn$adj_p_12<0.05 | p_value_dunn$adj_p_13<0.05 |p_value_dunn$adj_p_23<0.05,]




```

```{r drug}
prot_anno = read.xlsx("Results/TPDLibV2_8841_IPA.xlsx")

drug_target = prot_anno[!is.na(prot_anno$`Drug(s)`),]

prot_sig = sapply(P_sig_dunn$prot,function(v){strsplit(v,"_")[[1]][1]}) %>% as.vector()

drug_target = drug_target[drug_target$Matched.Term %in% prot_sig,]


df_drug = df_combine[uniprot %in% drug_target$Matched.Term,]

# df_drug = t(df_drug) %>% as.data.frame()
# df_drug$RFS = sinfo$`RFS（Month)`[match(row.names(df_drug),sinfo$MS_ID)] %>% as.numeric()
# df_drug$recur = sinfo$structure_recurrence[match(row.names(df_drug),sinfo$MS_ID)] %>% as.numeric()
# 
# df_drug = df_drug[!is.na(df_drug$RFS),]


## HPA database
HPA_annotation = read.delim("input/proteinatlas.tsv", sep = "\t",header = T)

# select FDA approaved drug only
drug_HPA = HPA_annotation[grepl("FDA",HPA_annotation$Protein.class) ,]
drug_HPA = drug_HPA[drug_HPA$Uniprot %in% prot_sig,]

df_drug_HPA = df_combine[uniprot %in% drug_HPA$Uniprot,]

# df_drug_HPA = t(df_drug_HPA) %>% as.data.frame()
# df_drug_HPA$RFS = sinfo$`RFS（Month)`[match(row.names(df_drug_HPA),sinfo$MS_ID)] %>% as.numeric()
# df_drug_HPA$recur = sinfo$structure_recurrence[match(row.names(df_drug_HPA),sinfo$MS_ID)] %>% as.numeric()

# df_drug_HPA = df_drug_HPA[!is.na(df_drug_HPA$RFS),]

unique(c(row.names(df_drug_HPA),row.names(df_drug))) %>% length() ## 626 prot

target_prot = unique(c(row.names(df_drug_HPA),row.names(df_drug)))

df_drug626 =  df_combine[row.names(df_combine) %in% target_prot,]

df_drug626 = t(df_drug626) %>% as.data.frame()
df_drug626$RFS = sinfo$`RFS（Month)`[match(row.names(df_drug626),sinfo$MS_ID)] %>% as.numeric()
df_drug626$recur = sinfo$structure_recurrence[match(row.names(df_drug626),sinfo$MS_ID)] %>% as.numeric()
df_drug626 = df_drug626[!is.na(df_drug626$RFS),]


univ_results = data.frame()

for (i in 1:626) {
  
  covariates <- names(df_drug626)[i]  # risk factors
  univ_formulas <- as.formula(paste('Surv(RFS, recur)~',covariates))
  univ_models <- coxph(univ_formulas, df_drug626)
  
  x <- summary(univ_models)
  n = x$n
  likelihood.pvalue <- signif(x$logtest['pvalue'], digits = 3) %>% as.numeric()
  # log.test <- signif(x$logtest["test"], digits = 2)
  wald.pvalue <- signif(x$wald['pvalue'], digits = 3)  %>% as.numeric()
  # wald.test <- signif(x$wald["test"], digits = 2)
  score.pvalue <- signif(x$sctest['pvalue'], digits = 3) %>% as.numeric()
  # score.test <- signif(x$sctest["test"], digits = 2)
  beta <- signif(x$coef[1], digits=2);
  HR <- signif(x$coef[2], digits=2);
  HR.confint.lower <- signif(x$conf.int[,"lower .95"],2)
  HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
  HR <- paste0(HR, " (", 
               HR.confint.lower, "-", HR.confint.upper, ")")
  res<-c(n,beta, HR, likelihood.pvalue, wald.pvalue,score.pvalue)

  univ_results = rbind(univ_results,res)

}

names(univ_results)<-c("count","beta", "HR (95% CI for HR)",           
                       "likelihood.pvalue", "wald.pvalue", "score.pvalue")

row.names(univ_results) = names(df_drug626)[1:626]

univ_results$adj_p_score = p.adjust(univ_results$score.pvalue, method = "BH")

uni_cox_sig = univ_results[univ_results$adj_p_score<0.05,]

df_drug_sig626 = df_drug626[,(names(df_drug626) %in% row.names(uni_cox_sig))]


DEPs_R = read.table("Results/DEPs_20240424/DEPs_lm_RvsNR_20240424.csv", sep = ",",
                    header = T,row.names = 1)

UP_R = DEPs_R$Prot[grepl("Up",DEPs_R$threshold)]
df_drug_sig626 = df_drug_sig626[,names(df_drug_sig626) %in% UP_R]
df_drug_sig626 = cbind(df_drug_sig626,df_drug626[,627:628])

### multivariate_cox
covariates <- names(df_drug_sig626)[1:12]  # risk factors
univ_formulas <- as.formula(paste('Surv(RFS, recur)~',paste0(covariates,collapse = " + ")))
res.cox <- coxph(univ_formulas, df_drug626)

res.cox
X = summary(res.cox)


```

```{r heatmap}
#df_drug_ht_HPA = df_drug_sig690[,covariates[X[["coefficients"]][,5]<0.05]]
df_drug_ht_HPA = df_drug_sig626[,covariates]
df_drug_ht_HPA = t(df_drug_ht_HPA) %>% as.data.frame()

annot = data.frame(recur = sinfo$structure_recurrence[match(names(df_drug_ht_HPA),sinfo$MS_ID)],
                   cluster = cluster$cluster[match(names(df_drug_ht_HPA),cluster$sample)]) 

annot$sample = names(df_drug_ht_HPA)

annot[,1:2] = apply(annot[,1:2],2,as.numeric)

annot = annot[order(annot$recur,annot$cluster),]
annot$combine = paste0(annot$recur,"_",annot$cluster)




# df_drug_ht_HPA = data.frame(t(df_drug_ht_HPA))
df_drug_ht_mean_HPA = data.frame(row.names(df_drug_ht_HPA))

n=2
for (i in unique(annot$combine)) {
  x = apply(df_drug_ht_HPA,1,function(x){mean(x[names(df_drug_ht_HPA) %in% annot$sample[annot$combine == i]])})
  df_drug_ht_mean_HPA[,n] = x
  n=n+1}

names(df_drug_ht_mean_HPA)[2:7] = unique(annot$combine)



row.names(df_drug_ht_mean_HPA) = df_drug_ht_mean_HPA[,1]
df_drug_ht_mean_HPA = df_drug_ht_mean_HPA[,-1]

annot1 = data.frame(recur = c("0","0","0","1","1","1"),cluster = c("1","2","3","1","2","3"))


library(gt)

mcox = data.frame(prot = names(df_drug_sig626)[1:12],
                  HR = summary(res.cox)$coefficients[,2],
                  pvalue = summary(res.cox)$coefficients[,5],
                  HR.confint.lower = summary(res.cox)$conf.int[,3],
                  HR.confint.upper = summary(res.cox)$conf.int[,4])

mcox$log2HR = log2(mcox$HR)
mcox$log2HR_lower = log2(mcox$HR.confint.lower)
mcox$log2HR_upper = log2(mcox$HR.confint.upper)

mcox = mcox[order(mcox$log2HR,decreasing = T),]


centermatrix <- scale(t(df_drug_ht_mean_HPA))
testdata <- data.frame(centermatrix)
testdata2 <- t(testdata)

pdf("Results/drug/heatmap_12drug_mean_DEPS_R_20250304.pdf",
    height = 5, width = 5)
ht1 = Heatmap(testdata2,  cluster_columns = F, #dend_hc3, # row_split = 3,  #column_split = 3, #dend_hc3, 
              # cluster_row_slices = FALSE,cluster_column_slices = FALSE,
              # row_title = "cluster_within_group", 
              col =  c(brewer.pal(11,"RdBu")[11:7],"azure1",brewer.pal(11,"RdBu")[5:1]),
              cluster_rows = T,show_row_names  = T, show_column_names = F,
              show_column_dend = T, show_row_dend = T, 
              top_annotation = HeatmapAnnotation(structure_recurrence = annot1$recur,
                                                 cluster = annot1$cluster,
                                                 # hospital = lee_clu3_exf$hospital,
                                                 col = list(structure_recurrence = c("0" = "#57C3EA","1" = "#E66563"),
                                                            cluster = c("1" = "#C1D57F","2" = "#A264A6","3" = "pink")
                                                            ),
                                                 show_annotation_name = T,show_legend = T,
                                                 simple_anno_size = unit(0.5, "cm")
                                                 # annotation_legend_param = list(structure_recurrence = list(nrow = 1),
                                                 #                                disease_specific_death = list(nrow = 1)
                                                 #)
                                                 #gp = gpar(col = "black")
              ),
              heatmap_legend_param = list(title = "z-score", direction = "horizontal"))

draw(ht1, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")
dev.off()

## forest plot
ht2 = draw(ht1)
mcox_sig_up = mcox[rownames(df_drug_ht_mean_HPA)[row_order(ht2)],]
mcox_sig_up$prot = factor(mcox_sig_up$prot,levels = mcox_sig_up$prot)

pdf("Results/drug/forest_12drug_DEPS_R_20250304.pdf", height = 5, width = 3)
  mcox_sig_up |>
  ggplot(aes(y = fct_rev(prot))) + 
  theme_classic() +
  geom_point(aes(x=log2HR), shape=15, size=3) +
  geom_linerange(aes(xmin=log2HR_lower, xmax=log2HR_upper)) +
  geom_vline(xintercept = 0, linetype="dashed") +
  labs(x="Log Hazard Ratio", y="")+
  coord_cartesian(ylim=c(1,13), xlim=c(-1, 3)) +
  scale_x_continuous(name ="log2(hazard ratio)",seq(-10,8,2)) +
  # annotate("text", x = -3, y = 13, label = "Protective") +
  annotate("text", x = 5, y = 13, label = "Risk scores") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y= element_blank(),
        axis.text.y= element_blank(),
        axis.title.y= element_blank())
dev.off()





```

